{{ if .Values.expose.enabled}}
apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: {{ include "susaas-router.fullname" . }}
  labels: {{- include "susaas-router.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.global.gateway | default "kyma-system/kyma-gateway" }}
  hosts: 
    - {{ printf "%s.%s" ( include "susaas-router.exposeHost" . ) $.Values.global.domain }}
  rules:
  - methods:
      - GET
      - POST
      - PUT
      - DELETE
      - HEAD
    path: /*
    noAuth: true
  service:
    name: {{ include "susaas-router.fullname" . }}
    port: {{ .Values.port }}
{{ end }}

