{{ if .Values.expose.enabled }}
apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: {{ include "susaas-broker.fullname" . }}
  labels: {{- include "susaas-broker.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.global.gateway | default "kyma-system/kyma-gateway" }}
  hosts:
    - {{ printf "%s.%s" ( include "susaas-broker.exposeHost" . ) $.Values.global.domain }}
  rules:
  - methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"]
    path: /*
    noAuth: true
  service:
    name: {{ include "susaas-broker.fullname" . }}
    port: {{ .Values.port }}
{{ end }}
