@xsuaaHostname = <<uaa.url in service key>>
@btpXsuaaClient = <<uaa.clientid in service key>>
@btpXsuaaSecret = <<uaa.clientsecret in service key>>
@apiEndpoint = http://localhost:4004


##########################################
# Get SAP XSUAA token 
##########################################

# @name getXsuaaToken

POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{btpXsuaaClient}}:{{btpXsuaaSecret}}

client_id={{btpXsuaaClient}}
&client_secret={{btpXsuaaSecret}}
&grant_type=client_credentials


##########################################
# Call CAP endpoint (BTP)
##########################################

@access_token = {{getXsuaaToken.response.body.$.access_token}}

# @name uploadProductsBtp
POST {{apiEndpoint}}/rest/api/bulkUpsertProducts
Authorization: Bearer {{access_token}}
Content-type: application/json

{
      "products" : [
            {"ID":"HT-1000","typeCode":"PR","category":"Notebooks","supplierId":"0100000046","taxTarifCode":1,"measureUnit":"EA","weightMeasure":4.2,"weightUnit":"KG","price":956,"text":"Notebook Basic 15","language_code":"E","currency_code":"EUR"},
            {"ID":"HT-1001","typeCode":"PR","category":"Notebooks","supplierId":"0100000047","taxTarifCode":1,"measureUnit":"EA","weightMeasure":4.5,"weightUnit":"KG","price":1249,"text":"Notebook Basic 17","language_code":"E","currency_code":"EUR"},
            {"ID":"HT-1002","typeCode":"PR","category":"Notebooks","supplierId":"0100000048","taxTarifCode":1,"measureUnit":"EA","weightMeasure":4.2,"weightUnit":"KG","price":1570,"text":"Notebook Basic 18","language_code":"E","currency_code":"USD"},
            {"ID":"HT-1003","typeCode":"PR","category":"Notebooks","supplierId":"0100000049","taxTarifCode":1,"measureUnit":"EA","weightMeasure":4.2,"weightUnit":"KG","price":1650,"text":"Notebook Basic 19","language_code":"E","currency_code":"EUR"},
            {"ID":"HT-1055","typeCode":"PR","category":"Multifunction Printers","supplierId":"0100000069","taxTarifCode":1,"measureUnit":"EA","weightMeasure":6.3,"weightUnit":"KG","price":99,"text":"Multi Print","language_code":"E","currency_code":"EUR"},
            {"ID":"HT-1056","typeCode":"PR","category":"Multifunction Printers","supplierId":"0100000070","taxTarifCode":1,"measureUnit":"EA","weightMeasure":4.3,"weightUnit":"KG","price":119,"text":"Multi Color","language_code":"E","currency_code":"JPY"},
            {"ID":"HT-1060","typeCode":"PR","category":"Mice","supplierId":"0100000071","taxTarifCode":1,"measureUnit":"EA","weightMeasure":0.09,"weightUnit":"KG","price":9,"text":"Cordless Mouse","language_code":"E","currency_code":"EUR"},
            {"ID":"HT-1063","typeCode":"PR","category":"Keyboards","supplierId":"0100000074","taxTarifCode":1,"measureUnit":"EA","weightMeasure":2.1,"weightUnit":"KG","price":14,"text":"Ergonomic Keyboard","language_code":"E","currency_code":"BRL"},
            {"ID":"HT-1120","typeCode":"PR","category":"Keyboards","supplierId":"0100000065","taxTarifCode":1,"measureUnit":"EA","weightMeasure":1,"weightUnit":"KG","price":29,"text":"Cordless Bluetooth Keyboard","language_code":"0","currency_code":"EUR"}
      ]
}

##########################################

# @name uploadProductsExtendedBtp
POST {{apiEndpoint}}/rest/api/bulkUpdateProducts
Authorization: Bearer {{access_token}}
Content-type: application/json

{
      "products" : [
            {"ID": "HT-1000","eolProductDesign": 43,"traditionalSalesShare": 82,"repairSalesShare": 8,"resellSalesShare": 10},
            {"ID": "HT-1001","eolProductDesign": 38,"traditionalSalesShare": 97,"repairSalesShare": 3,"resellSalesShare": 0},
            {"ID": "HT-1002","eolProductDesign": 35,"traditionalSalesShare": 87,"repairSalesShare": 5,"resellSalesShare": 8},
            {"ID": "HT-1003","eolProductDesign": 42,"traditionalSalesShare": 74,"repairSalesShare": 20,"resellSalesShare": 6},
            {"ID": "HT-1055","eolProductDesign": 56,"traditionalSalesShare": 98,"repairSalesShare": 1,"resellSalesShare": 1},
            {"ID": "HT-1056","eolProductDesign": 49,"traditionalSalesShare": 95,"repairSalesShare": 3,"resellSalesShare": 2},
            {"ID": "HT-1060","eolProductDesign": 25,"traditionalSalesShare": 99,"repairSalesShare": 0,"resellSalesShare": 1},
            {"ID": "HT-1063","eolProductDesign": 34,"traditionalSalesShare": 97,"repairSalesShare": 1,"resellSalesShare": 2},
            {"ID": "HT-1120","eolProductDesign": 28,"traditionalSalesShare": 95,"repairSalesShare": 2.5,"resellSalesShare": 2.5}
      ]
}

##########################################
# Call CAP endpoint (BTP)
##########################################

@access_token = {{getXsuaaToken.response.body.$.access_token}}

# @name uploadRecyclingCountriesBtp
POST {{apiEndpoint}}/rest/api/bulkUpsertRecyclingCountries
Authorization: Bearer {{access_token}}
Content-type: application/json

{
      "recyclingCountries" : [
            {"product_ID":"HT-1000","country_code":"DE","eolRecyclability":54},
            {"product_ID":"HT-1000","country_code":"JP","eolRecyclability":20},
            {"product_ID":"HT-1000","country_code":"US","eolRecyclability":15},
            {"product_ID":"HT-1001","country_code":"DE","eolRecyclability":54},
            {"product_ID":"HT-1001","country_code":"JP","eolRecyclability":20},
            {"product_ID":"HT-1001","country_code":"US","eolRecyclability":15},
            {"product_ID":"HT-1002","country_code":"DE","eolRecyclability":54},
            {"product_ID":"HT-1003","country_code":"DE","eolRecyclability":54},
            {"product_ID":"HT-1055","country_code":"DE","eolRecyclability":54},
            {"product_ID":"HT-1055","country_code":"DK","eolRecyclability":61},
            {"product_ID":"HT-1056","country_code":"DE","eolRecyclability":54},
            {"product_ID":"HT-1056","country_code":"UK","eolRecyclability":57},
            {"product_ID":"HT-1060","country_code":"JP","eolRecyclability":20},
            {"product_ID":"HT-1060","country_code":"US","eolRecyclability":15},
            {"product_ID":"HT-1063","country_code":"DK","eolRecyclability":61},
            {"product_ID":"HT-1063","country_code":"JP","eolRecyclability":20},
            {"product_ID":"HT-1063","country_code":"US","eolRecyclability":15},
            {"product_ID":"HT-1120","country_code":"DE","eolRecyclability":54}
      ]
}

# @name uploadRecyclingMaterialsBtp
POST {{apiEndpoint}}/rest/api/bulkUpsertRecyclingMaterials
Authorization: Bearer {{access_token}}
Content-type: application/json

{
      "recyclingMaterials" : [
            {"product_ID":"HT-1000","material":"MT10000001","materialName":"Aluminium","weightShare":14,"recycleShare":23},
            {"product_ID":"HT-1000","material":"MT20000008","materialName":"Plastic","weightShare":34,"recycleShare":30},
            {"product_ID":"HT-1001","material":"MT10000001","materialName":"Aluminium","weightShare":10,"recycleShare":23},
            {"product_ID":"HT-1001","material":"MT20000008","materialName":"Plastic","weightShare":44,"recycleShare":39},
            {"product_ID":"HT-1002","material":"MT10000001","materialName":"Aluminium","weightShare":21,"recycleShare":40},
            {"product_ID":"HT-1002","material":"MT20000008","materialName":"Plastic","weightShare":28,"recycleShare":38},
            {"product_ID":"HT-1003","material":"MT10000001","materialName":"Aluminium","weightShare":32,"recycleShare":43},
            {"product_ID":"HT-1003","material":"MT20000008","materialName":"Plastic","weightShare":38,"recycleShare":56},
            {"product_ID":"HT-1055","material":"MT10000001","materialName":"Aluminium","weightShare":8,"recycleShare":75},
            {"product_ID":"HT-1055","material":"MT20000008","materialName":"Plastic","weightShare":63,"recycleShare":15},
            {"product_ID":"HT-1056","material":"MT10000001","materialName":"Aluminium","weightShare":12,"recycleShare":56},
            {"product_ID":"HT-1056","material":"MT20000008","materialName":"Plastic","weightShare":63,"recycleShare":12},
            {"product_ID":"HT-1060","material":"MT10000001","materialName":"Aluminium","weightShare":3,"recycleShare":3},
            {"product_ID":"HT-1060","material":"MT20000008","materialName":"Plastic","weightShare":69,"recycleShare":11},
            {"product_ID":"HT-1063","material":"MT10000001","materialName":"Aluminium","weightShare":23,"recycleShare":10},
            {"product_ID":"HT-1063","material":"MT20000008","materialName":"Plastic","weightShare":61,"recycleShare":28},
            {"product_ID":"HT-1120","material":"MT10000001","materialName":"Aluminium","weightShare":22,"recycleShare":15},
            {"product_ID":"HT-1120","material":"MT20000008","materialName":"Plastic","weightShare":70,"recycleShare":33}
      ]
}

# @name uploadSalesOrdersBtp
POST {{apiEndpoint}}/rest/api/bulkUpsertSalesOrders
Authorization: Bearer {{access_token}}
Content-type: application/json

{
    "salesOrders" : [
        {"so": "0500000000","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 1137.64,"taxAmount": 181.64,"netAmount": 956,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000000","soItemPos": "0000000020","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000000","soItemPos": "0000000030","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000000","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3927,"taxAmount": 627,"netAmount": 3300,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000002","soItemPos": "0000000070","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 117.81,"taxAmount": 18.81,"netAmount": 99,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000002","soItemPos": "0000000080","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "JPY","country_code": "DE","language_code": "E" },
        {"so": "0500000007","soItemPos": "0000000070","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3412.92,"taxAmount": 544.92,"netAmount": 2868,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000004","companyName": "Panorama Studios","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "US","language_code": "E" },
        {"so": "0500000007","soItemPos": "0000000080","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 1486.31,"taxAmount": 237.31,"netAmount": 1249,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000004","companyName": "Panorama Studios","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "US","language_code": "E" },
        {"so": "0500000008","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 21.42,"taxAmount": 3.42,"netAmount": 18,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "AR","language_code": "E" },
        {"so": "0500000008","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 49.98,"taxAmount": 7.98,"netAmount": 42,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "BRL","country_code": "AR","language_code": "E" },
        {"so": "0500000012","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2275.28,"taxAmount": 363.28,"netAmount": 1912,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000012","soItemPos": "0000000020","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000012","soItemPos": "0000000030","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000012","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 5890.5,"taxAmount": 940.5,"netAmount": 4950,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000015","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 353.43,"taxAmount": 56.43,"netAmount": 297,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "MX","language_code": "E" },
        {"so": "0500000015","soItemPos": "0000000020","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "JPY","country_code": "MX","language_code": "E" },
        {"so": "0500000015","soItemPos": "0000000030","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 10.71,"taxAmount": 1.71,"netAmount": 9,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "MX","language_code": "E" },
        {"so": "0500000015","soItemPos": "0000000060","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 16.66,"taxAmount": 2.66,"netAmount": 14,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "BRL","country_code": "MX","language_code": "E" },
        {"so": "0500000030","soItemPos": "0000000010","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 1137.64,"taxAmount": 181.64,"netAmount": 956,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000030","soItemPos": "0000000020","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000030","soItemPos": "0000000030","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000030","soItemPos": "0000000040","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 3927,"taxAmount": 627,"netAmount": 3300,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000032","soItemPos": "0000000070","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 117.81,"taxAmount": 18.81,"netAmount": 99,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000032","soItemPos": "0000000080","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "JPY","country_code": "DE","language_code": "E" },
        {"so": "0500000037","soItemPos": "0000000070","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 3412.92,"taxAmount": 544.92,"netAmount": 2868,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000004","companyName": "Panorama Studios","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "US","language_code": "E" },
        {"so": "0500000037","soItemPos": "0000000080","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 1486.31,"taxAmount": 237.31,"netAmount": 1249,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000004","companyName": "Panorama Studios","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "US","language_code": "E" },
        {"so": "0500000038","soItemPos": "0000000010","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 21.42,"taxAmount": 3.42,"netAmount": 18,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "AR","language_code": "E" },
        {"so": "0500000038","soItemPos": "0000000040","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 49.98,"taxAmount": 7.98,"netAmount": 42,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "BRL","country_code": "AR","language_code": "E" },
        {"so": "0500000042","soItemPos": "0000000010","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 2275.28,"taxAmount": 363.28,"netAmount": 1912,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000042","soItemPos": "0000000020","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000042","soItemPos": "0000000030","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000042","soItemPos": "0000000040","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 5890.5,"taxAmount": 940.5,"netAmount": 4950,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000045","soItemPos": "0000000010","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 353.43,"taxAmount": 56.43,"netAmount": 297,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "MX","language_code": "E" },
        {"so": "0500000045","soItemPos": "0000000020","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "JPY","country_code": "MX","language_code": "E" },
        {"so": "0500000045","soItemPos": "0000000030","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 10.71,"taxAmount": 1.71,"netAmount": 9,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "MX","language_code": "E" },
        {"so": "0500000045","soItemPos": "0000000060","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 16.66,"taxAmount": 2.66,"netAmount": 14,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "BRL","country_code": "MX","language_code": "E" },
        {"so": "0500000054","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 103.53,"taxAmount": 16.53,"netAmount": 87,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1120","category": "Keyboards","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Cordless Bluetooth Keyboard","itemAtpStatus": null,"firstName": null,"lastName": null,"overallStatus": null,"currency_code": "EUR","country_code": null,"language_code": null },
        {"so": "0500000055","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 1137.64,"taxAmount": 181.64,"netAmount": 956,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000055","soItemPos": "0000000020","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000055","soItemPos": "0000000030","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000055","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3927,"taxAmount": 627,"netAmount": 3300,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000057","soItemPos": "0000000070","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 117.81,"taxAmount": 18.81,"netAmount": 99,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000057","soItemPos": "0000000080","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "JPY","country_code": "DE","language_code": "E" },
        {"so": "0500000062","soItemPos": "0000000070","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3412.92,"taxAmount": 544.92,"netAmount": 2868,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000006","companyName": "Asia High tech","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "JP","language_code": "E" },
        {"so": "0500000062","soItemPos": "0000000080","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 1486.31,"taxAmount": 237.31,"netAmount": 1249,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000006","companyName": "Asia High tech","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "JP","language_code": "E" },
        {"so": "0500000063","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 21.42,"taxAmount": 3.42,"netAmount": 18,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "AR","language_code": "E" },
        {"so": "0500000063","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 49.98,"taxAmount": 7.98,"netAmount": 42,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "BRL","country_code": "AR","language_code": "E" },
        {"so": "0500000067","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2275.28,"taxAmount": 363.28,"netAmount": 1912,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000067","soItemPos": "0000000020","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000067","soItemPos": "0000000030","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000067","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 5890.5,"taxAmount": 940.5,"netAmount": 4950,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000080","soItemPos": "0000000010","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 1137.64,"taxAmount": 181.64,"netAmount": 956,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000080","soItemPos": "0000000020","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000080","soItemPos": "0000000030","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000080","soItemPos": "0000000040","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 3927,"taxAmount": 627,"netAmount": 3300,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000000","companyName": "SAP","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000082","soItemPos": "0000000070","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 117.81,"taxAmount": 18.81,"netAmount": 99,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000082","soItemPos": "0000000080","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "JPY","country_code": "DE","language_code": "E" },
        {"so": "0500000087","soItemPos": "0000000070","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 3412.92,"taxAmount": 544.92,"netAmount": 2868,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000004","companyName": "Panorama Studios","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "US","language_code": "E" },
        {"so": "0500000087","soItemPos": "0000000080","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 1486.31,"taxAmount": 237.31,"netAmount": 1249,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000004","companyName": "Panorama Studios","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "US","language_code": "E" },
        {"so": "0500000088","soItemPos": "0000000010","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 21.42,"taxAmount": 3.42,"netAmount": 18,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "EUR","country_code": "AR","language_code": "E" },
        {"so": "0500000088","soItemPos": "0000000040","lifecycleStatus": "C","billingStatus": "P","deliveryStatus": "D","grossAmount": 49.98,"taxAmount": 7.98,"netAmount": 42,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "P","currency_code": "BRL","country_code": "AR","language_code": "E" },
        {"so": "0500000092","soItemPos": "0000000010","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 2275.28,"taxAmount": 363.28,"netAmount": 1912,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000092","soItemPos": "0000000020","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000092","soItemPos": "0000000030","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000092","soItemPos": "0000000040","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 5890.5,"taxAmount": 940.5,"netAmount": 4950,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000095","soItemPos": "0000000010","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 353.43,"taxAmount": 56.43,"netAmount": 297,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "MX","language_code": "E" },
        {"so": "0500000095","soItemPos": "0000000020","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "JPY","country_code": "MX","language_code": "E" },
        {"so": "0500000095","soItemPos": "0000000030","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 10.71,"taxAmount": 1.71,"netAmount": 9,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "EUR","country_code": "MX","language_code": "E" },
        {"so": "0500000095","soItemPos": "0000000060","lifecycleStatus": "P","billingStatus": null,"deliveryStatus": "D","grossAmount": 16.66,"taxAmount": 2.66,"netAmount": 14,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000008","companyName": "AVANTEL","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "D","currency_code": "BRL","country_code": "MX","language_code": "E" },
        {"so": "0500000104","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 103.53,"taxAmount": 16.53,"netAmount": 87,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1120","category": "Keyboards","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Cordless Bluetooth Keyboard","itemAtpStatus": null,"firstName": null,"lastName": null,"overallStatus": null,"currency_code": "EUR","country_code": null,"language_code": null },
        {"so": "0500000105","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 1137.64,"taxAmount": 181.64,"netAmount": 956,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000105","soItemPos": "0000000020","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000105","soItemPos": "0000000030","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000105","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3927,"taxAmount": 627,"netAmount": 3300,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000107","soItemPos": "0000000070","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 117.81,"taxAmount": 18.81,"netAmount": 99,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1055","category": "Multifunction Printers","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Multi Print","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000107","soItemPos": "0000000080","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 283.22,"taxAmount": 45.22,"netAmount": 238,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1056","category": "Multifunction Printers","bpRole": "01","bpId": "0100000003","companyName": "Talpa","text": "Multi Color","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "JPY","country_code": "DE","language_code": "E" },
        {"so": "0500000112","soItemPos": "0000000070","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3412.92,"taxAmount": 544.92,"netAmount": 2868,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000006","companyName": "Asia High tech","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "JP","language_code": "E" },
        {"so": "0500000112","soItemPos": "0000000080","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 1486.31,"taxAmount": 237.31,"netAmount": 1249,"quantity": 1,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000006","companyName": "Asia High tech","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "JP","language_code": "E" },
        {"so": "0500000113","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 21.42,"taxAmount": 3.42,"netAmount": 18,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1060","category": "Mice","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Cordless Mouse","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "AR","language_code": "E" },
        {"so": "0500000113","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 49.98,"taxAmount": 7.98,"netAmount": 42,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1063","category": "Keyboards","bpRole": "01","bpId": "0100000009","companyName": "Telecomunicaciones Star","text": "Ergonomic Keyboard","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "BRL","country_code": "AR","language_code": "E" },
        {"so": "0500000117","soItemPos": "0000000010","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2275.28,"taxAmount": 363.28,"netAmount": 1912,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1000","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 15","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000117","soItemPos": "0000000020","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 2972.62,"taxAmount": 474.62,"netAmount": 2498,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1001","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 17","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" },
        {"so": "0500000117","soItemPos": "0000000030","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 3736.6,"taxAmount": 596.6,"netAmount": 3140,"quantity": 2,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1002","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 18","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "USD","country_code": "DE","language_code": "E" },
        {"so": "0500000117","soItemPos": "0000000040","lifecycleStatus": "N","billingStatus": null,"deliveryStatus": null,"grossAmount": 5890.5,"taxAmount": 940.5,"netAmount": 4950,"quantity": 3,"quantityUnit": "EA","deliveryDate": "2022-07-14T07:00:00.000Z","product_ID": "HT-1003","category": "Notebooks","bpRole": "01","bpId": "0100000005","companyName": "TECUM","text": "Notebook Basic 19","itemAtpStatus": null,"firstName": "EPM","lastName": "User","overallStatus": "N","currency_code": "EUR","country_code": "DE","language_code": "E" }
    ]
}