apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: susaas-app-logs
spec:
  input:
    application:
      containers:
        exclude:
          - istio-proxy
      namespaces:
        include:
          - susaas
  output:
    http:
      dedot: true
      host:
        valueFrom:
          secretKeyRef:
            name: susaas-logging
            namespace: susaas
            key: ingest-mtls-endpoint
      tls:
        cert:
          valueFrom:
            secretKeyRef:
              name: susaas-logging
              namespace: susaas
              key: ingest-mtls-cert
        key:
          valueFrom:
            secretKeyRef:
              name: susaas-logging
              namespace: susaas
              key: ingest-mtls-key
      uri: /customindex/kyma