{{- if and .Values.expose.enabled ( not .Values.apim ) }}
apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: {{ include "susaas-api.fullname" . }}
  labels: {{- include "susaas-api.labels" . | nindent 4 }}
spec:
  gateway: {{ .Values.global.gateway | default "kyma-system/kyma-gateway" }}
  hosts: 
    - {{ printf "%s.%s" ( include "susaas-api.exposeHost" . ) $.Values.global.domain }}
  rules:
  - methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"]
    path: /*
    noAuth: true
  service:
    name: {{ include "susaas-api.fullname" . }}
    port: {{ .Values.port }}
{{- end }}
