{{- if or (not (hasKey .Values.hpa "enabled")) .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "susaas-srv.fullname" . }}
  labels: {{- include "susaas-srv.labels" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.hpa.minReplicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "susaas-srv.fullname" . }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
      {{- if .Values.hpa.cpuTargetAverageValue }}
        type: AverageValue
        averageValue: {{ .Values.hpa.cpuTargetAverageValue }}
      {{- else }}
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuTargetAverageUtilization }}
      {{- end }}
{{- end }}