global:
  imagePullSecret: {}
  image: {}
  partOf: susaas
  component: srv
  domain: 
  gateway: 
  broker:
    fullName: 
    deploymentHost:
  router:
    name: 
    fullName: 
    deploymentHost:
    port: 
  
port: 8080

serviceAccount:
  enabled: true # If true, own serviceAccount (<<ReleaseName>>-srv) used by pod, otherwise "default" serviceAccount
  automountToken: true # If true, token of the assigned serviceAccount (default or fullname) automounted
  roleBinding:
    enabled: true # If true, own clusterRole (<<ReleaseName>>-srv) bound to own serviceAccount (<<ReleaseName>>-srv)

image: {}
imagePullSecret: {}
additionalVolumes: []

expose:
  enabled: true

# High-Availability Settings
ha:
  enabled: true
  pdb:
    minAvailable: 1

hpa:
  enabled: true
  minReplicaCount: 1 # To use High-Availability set minReplicaCount to at least 2
  maxReplicaCount: 3
  cpuTargetAverageUtilization: 80
  cpuTargetAverageValue:

health_check:
  liveness:
    path: /healthz
  readiness:
    path: /healthz
  
securityContext:
  user: 1002
  group: 1000

startupTimeout: 60
resources:
  limits:
    ephemeral-storage: 
    memory: 
  requests:
    ephemeral-storage: 
    cpu: 
    memory: 

envSecretNames: []

envSecretNamesTpl: 
  - "{{ .Release.Name }}-broker"

env:
  cds_features: '{ "emulate_vcap_services" : true }'
  KYMA_APIRULE_GROUP: gateway.kyma-project.io
  KYMA_APIRULE_VERSION: v1beta1
  KYMA_APIRULE_PLURAL: apirules
  KYMA_DEPLOYMENT: 'true'

envTpl:
  SERVICE_REPLACEMENTS: '[{ "key" : "com-hdi-container", "service" : "common-db" }]'