apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-broker-secret
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  BROKER_USER : {{ "broker-user" | b64enc | quote }}
  {{- $password := (randAlphaNum 32  | b64enc ) }}
  BROKER_PASSWORD : {{ $password | quote }}
  {{- $salt := ( randAlphaNum 32  ) }}
  {{- $hash := printf "sha256:%s:%s" ( $salt | b64enc ) ( ( printf "%s%s" $salt $password ) | sha256sum | b64enc )  }}
  BROKER_HASH : {{ $hash | b64enc | quote }}